### ISSUE TITLE
Solr 8 container always restart

### ISSUE THREAD

**Issue by svicervlad** [jet-dev-team/drupal-dockerizer#45]
When i configure drupal-dockerizer.yml with solr setup. Container does not work correctly

**Steps to reproduce:**
- run `ansible-playbook main.yml -K`

**Expected behavior**
Container with solr should work correctly

**Terminal Output or Screenshots**
```bash
Cannot write to /var/solr as 1000:1000
drwxrwx--- 1 8983 root 36 Apr 21 13:06 /var/solr
```

**Configuration**
```yml
solr: true
solr_configs_path: 'path/to/solr/configuration'
solr_version: 8
```

**Environment:**
 - OS: archlinux
 - Drupal Dockerizer version latest `main`
 - Docker version 20.10.6, build 370c28948e
 - Docker compose version 1.29.1
 - Ansible version 2.10.8
 - Browser is not important
